### ISSUE TITLE
Allow (sam)name as input attribute for datasource ad_computer

### ISSUE THREAD

**Issue by jpatigny** [hashicorp/terraform-provider-ad#115]
### Description

Currently only GUID and DN are allowed as input parameter for datasource ad_computer.
It would be nice to retrieve attributes based on computer name and/or sam account name.

For example, I would need to retrieve Distinguished name based on computer name.

### Potential Terraform Configuration

```hcl
data "ad_computer" "c" {
    name = "test123"
}

data "ad_computer" "d" {
    sam_account_name = "test123"
}

output "computer_guid" {
  value = data.ad_computer.c.guid
}

output "computer2_guid" {
  value = data.ad_computer.d.guid
}
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by AspenForester** [comment]
Anything that `Get-ADComputer` can take in the `-Identity` parameter should be fair game.

**Comment by jpatigny** [comment]
Implemented with MR 118. 
Thanks for the work 👍🏻
