### ISSUE TITLE
Manage group membership.

### ISSUE THREAD

**Issue by koikonom** [hashicorp/terraform-provider-ad#33]
Add a new `groups` field in the `ad_user` resource that will correspond to a list of AD groups this user should be a member of.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by derhally** [comment]
What about a group_membership resource that provides one place for defining all members of a group?

**Comment by jweigand** [comment]
I realize it might add some complexity, but it would be ideal to manage group memberships both from the `ad_user` resource, and the `ad_group` resource. From the user, you should be able to define multiple groups, of which they would be a member. From a group, you should be able to define multiple users (or other groups) who are members of the group.

**Comment by rejackson73** [comment]
> What about a group_membership resource that provides one place for defining all members of a group?

Would this be incorporated into the current issue, or should this branch out to a new unique issue?

**Comment by koikonom** [comment]
Hello everyone! First I'd like to thank you all for your very valuable input.

After thinking about this for a bit it became obvious that my initial idea of managing group membership through the `ad_user` resource wouldn't be a good idea, since I'd have to manipulate the membership list of every group the user was a member of and we'd also require the user to be managed by terraform.

The opposite approach, passing a user list in the `ad_group` resource, is more efficient since we only manipulate a single group but it still required the group to be managed by terraform.

I think that introducing a new `group_membership` resource would address both shortcomings of my initial idea. It will take a group GUID and a list of user GUIDs as inputs and take all necessary actions once per group without requiring for the resources to be created by terraform.

Happy to hear your thoughts!

**Comment by derhally** [comment]
@koikonom  I think the group_membership makes sense to me, but i'm not sure about soley using the user's GUID as the input.  Not sure what your constraints are, but I like how the `Add-ADGroupMember` powershell cmdlet handles the members parameter. It lets you pass either a distinguished name, GUID, sid, or SAM account name.

**Comment by koikonom** [comment]
Yeah I think that could work too, since the `Identity` parameter takes all forms and figures it out on its own.

**Comment by briantist** [comment]
Please consider that not all members of a group are users. They may be other groups, computer objects, user/account objects, etc. and critically if you want it to work with cross-forest trusts: Foreign Security Principals.

The DSC resources for managing membership have just recently added support for external trusts so it may be helpful to see some of that: https://github.com/dsccommunity/ActiveDirectoryDsc/issues/619

**Comment by koikonom** [comment]
Implemented in v0.3.0.
