### ISSUE TITLE
Not a bug but a question

### ISSUE THREAD

**Issue by surajsub** [hashicorp/terraform-provider-ad#38]
I presume that in order to run this provider we will need access to a "machine" that can connect to the the AD server to execute the powershell commands. ? Is that correct 

or can we connect directly to the AD server to execute this provider

**Comment by aareet** [comment]
Hi @surajsub, if the computer you're on has access to the AD server via the WinRM credentials specified, that should be sufficient.

**Comment by surajsub** [comment]
Appreciate the response.. Will try and let you know . Still battling the 401 error

**Comment by koikonom** [comment]
Hi @surajsub, at the moment only local accounts are supported so in order for the operator to work you should give it the credentials of a local user running on the AD controller.

**Comment by aareet** [comment]
I'll close this for now, @surajsub let us know if you run into any issues using the provider.
