### ISSUE TITLE
gPCMachineExtensionNames isn't set on GPO attributes, causing them to not show and not apply

### ISSUE THREAD

**Issue by mdjx** [hashicorp/terraform-provider-ad#39]
### Terraform Version and Provider Version
Terraform v0.12.29
provider.ad v0.1.0

### Windows Version
Client, Windows 10 1909
Server, 2012 R2, 2019

### Affected Resource(s)
ad_gpo_security

### Terraform Configuration Files
```hcl
resource "ad_gpo" "example_gpo" {
    name   = "Event Log Retention Settings"
}

resource "ad_gpo_security" "example_gpo_sec" {
    gpo_container = ad_gpo.example_gpo.id

    application_log {
        maximum_log_size = 50048
    }
    system_log {
        maximum_log_size = 50048
    }
}
```

### Expected Behavior
GPO should be created with the correct event log settings

### Actual Behavior
GPO is created, but the settings are not visible in the 'Settings' tab of GPMC. The GPO does not apply correctly when linked. 

![](https://i.imgur.com/EPY7K7R.png)

However, once you  edit the GPO, they can be seen. 

![](https://i.imgur.com/DfsYj10.png)

### Steps to Reproduce
1. `terraform apply`
1. Check GPMC

### Important Factoids
This condiition is due to a missing `gPCMachineExtensionNames` value within AD for the GPO. It needs to be set to `[{827D319E-6EAC-11D2-A4EA-00C04F79F83A}{803E14A0-B4FB-11D0-A0D0-00A0C90F574B}]`. 

GPO Created with AD Provider: 

![](https://i.imgur.com/YSRCbDU.png)

Working GPO:

![](https://i.imgur.com/6l2lXyD.png)

This can be corrected with PowerShell:

`Set-ADObject -Identity "__GPO__DN__" -Replace @{gPCMachineExtensionNames="[{827D319E-6EAC-11D2-A4EA-00C04F79F83A}{803E14A0-B4FB-11D0-A0D0-00A0C90F574B}]"}`

For User settings, the attribute name is `gPCUserExtensionNames`. 

This issue is more complex then I have presented here, there are GUIDs for different types of settings, a (complete?) list can be found here: https://www.infrastructureheroes.org/microsoft-infrastructure/active-directory/guid-list-of-group-policy-client-extensions/. Different GPO settings will require different CSE GUIDs to be applied to the appropriate attribute (user/machine). 

Once the attribute value is set, the GPO shows (and applies) correctly. 

![](https://i.imgur.com/IA9WfAZ.png)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by aareet** [comment]
Thank you for reporting this @mdjx, we will work to fix this in our September release.

**Comment by koikonom** [comment]
Hi @mdjx , version 0.2.0 is out and it contains the fix for this issue.

Thank you!
