### ISSUE TITLE
Extra (+ custom) User Attributes

### ISSUE THREAD

**Issue by seahorseing-around** [hashicorp/terraform-provider-ad#58]
Pretty much as it says on the tin: This would be great for managing our test users, but without a broader set of attributes it's won't yet cut it!

It would need to include the standard set of AD native attributes, plus the ability to specify Custom ones we've added to the AD Schema, probably by providing the GUUID to accompany that attribute.

**Comment by santiagon610** [comment]
+1 to this, I'd absolutely be able to modify `givenName`, `sn`, `displayName`, `proxyAddresses`, `mail`, and the like
