### ISSUE TITLE
ad_group_membership does not accept and values for member

### ISSUE THREAD

**Issue by faisaleem-na** [hashicorp/terraform-provider-ad#67]
### Terraform Version and Provider Version
Terraform version: 0.13.4
AD provider version: 0.4.0

### Affected Resource(s)
- ad_group_membership

### Terraform Configuration Files
`
resource "ad_user" "u" {
    for_each            = var.svc_accounts
    principal_name      = each.value.principal_name
    sam_account_name    = each.value.sam_account_name
    display_name        = each.value.display_name
    container           = each.value.container   
    initial_password        = each.value.svc_password == null ? lookup(var.secret_value_output, each.value.secretname, "ERROR") : each.value.svc_password
    cannot_change_password  = each.value.cannot_change_password
    password_never_expires  = each.value.password_never_expires
    enabled                 = each.value.enable
}

resource "ad_group_membership" "gm" {
    for_each    = var.svc_accounts
    group_id = each.value.group_guid
    group_members  = [ ad_user.u[each.key].id ]
}`

### Debug Output
`Error: command Add-ADGroupMember exited with a non-zero exit code(1), stderr: #< CLIXML
<Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Loading Active Directory module for Windows PowerShell with default drive 'AD:'</AV><AI>0</AI><Nil /><PI>-1</PI><PC>0</PC><T>Processing</T><SR>-1</SR><SD> </SD></PR></MS></Obj><Obj S="progress" RefId="1"><TNRef RefId="0" /><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Loading Active Directory module for Windows PowerShell with default drive 'AD:'</AV><AI>0</AI><Nil /><PI>-1</PI><PC>25</PC><T>Processing</T><SR>-1</SR><SD> </SD></PR></MS></Obj><Obj S="progress" RefId="2"><TNRef RefId="0" /><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Loading Active Directory module for Windows PowerShell with default drive 'AD:'</AV><AI>0</AI><Nil /><PI>-1</PI><PC>50</PC><T>Processing</T><SR>-1</SR><SD> </SD></PR></MS></Obj><Obj S="progress" RefId="3"><TNRef RefId="0" /><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Loading Active Directory module for Windows PowerShell with default drive 'AD:'</AV><AI>0</AI><Nil /><PI>-1</PI><PC>75</PC><T>Processing</T><SR>-1</SR><SD> </SD></PR></MS></Obj><Obj S="progress" RefId="4"><TNRef RefId="0" /><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Loading Active Directory module for Windows PowerShell with default drive 'AD:'</AV><AI>0</AI><Nil /><PI>-1</PI><PC>100</PC><T>Processing</T><SR>-1</SR><SD> </SD></PR></MS></Obj><Obj S="progress" RefId="5"><TNRef RefId="0" /><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Loading Active Directory module for Windows PowerShell with default drive 'AD:'</AV><AI>0</AI><Nil /><PI>-1</PI><PC>100</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><Obj S="progress" RefId="6"><TNRef RefId="0" /><MS><I64 N="SourceId">2</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><S S="Error">Add-ADGroupMember : **Parameter cannot be processed because the parameter name 'Member' is ambiguous**. Possible matches _x000D__x000A_</S><S S="Error">include: -Members -MemberTimeToLive._x000D__x000A_</S><S S="Error">At line:1 char:68_x000D__x000A_</S><S S="Error">+ ... mber -Identity "ABROGATED" -Member svc.awe ..._x000D__x000A_</S><S S="Error">+`

### Expected Behavior
Member Should be added to group

### Actual Behavior
Stop Error occurs

### Important Factoids
i have tried supplying ID from the ad_user, GUID from the ad_user and both name and GUID by providing them as values for the variable but nothing seems to work and all produce the same result i.e parameter for member is ambiguous!

### References

- GH-1234

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jpatigny** [comment]
Could you provide the exact powershell command using the cmdlet "add-adgroupmember" by enabling trace logs ?
(Set environment variable TF_LOG = "TRACE"

**Comment by faisaleem-na** [comment]
> Could you provide the exact powershell command using the cmdlet "add-adgroupmember" by enabling trace logs ?
> (Set environment variable TF_LOG = "TRACE"

Hi,

i enabled the trace logging but i still cannot see the exact command it runs, all i get is this same log output regardless of log level

`<Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Loading Active Directory module for Windows PowerShell with default drive 'AD:'</AV><AI>0</AI><Nil /><PI>-1</PI><PC>0</PC><T>Processing</T><SR>-1</SR><SD> </SD></PR></MS></Obj><Obj S="progress" RefId="1"><TNRef RefId="0" /><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Loading Active Directory module for Windows PowerShell with default drive 'AD:'</AV><AI>0</AI><Nil /><PI>-1</PI><PC>25</PC><T>Processing</T><SR>-1</SR><SD> </SD></PR></MS></Obj><Obj S="progress" RefId="2"><TNRef RefId="0" /><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Loading Active Directory module for Windows PowerShell with default drive 'AD:'</AV><AI>0</AI><Nil /><PI>-1</PI><PC>50</PC><T>Processing</T><SR>-1</SR><SD> </SD></PR></MS></Obj><Obj S="progress" RefId="3"><TNRef RefId="0" /><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Loading Active Directory module for Windows PowerShell with default drive 'AD:'</AV><AI>0</AI><Nil /><PI>-1</PI><PC>75</PC><T>Processing</T><SR>-1</SR><SD> </SD></PR></MS></Obj><Obj S="progress" RefId="4"><TNRef RefId="0" /><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Loading Active Directory module for Windows PowerShell with default drive 'AD:'</AV><AI>0</AI><Nil /><PI>-1</PI><PC>100</PC><T>Processing</T><SR>-1</SR><SD> </SD></PR></MS></Obj><Obj S="progress" RefId="5"><TNRef RefId="0" /><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Loading Active Directory module for Windows PowerShell with default drive 'AD:'</AV><AI>0</AI><Nil /><PI>-1</PI><PC>100</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><Obj S="progress" RefId="6"><TNRef RefId="0" /><MS><I64 N="SourceId">2</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><S S="Error">Add-ADGroupMember : Parameter cannot be processed because the parameter name 'Member' is ambiguous. Possible matches _x000D__x000A_</S><S S="Error">include: -Members -MemberTimeToLive._x000D__x000A_</S><S S="Error">At line:1 char:68_x000D__x000A_</S><S S="Error">+ ... mber -Identity "726CC7A3-CDE9-4401-B0D0-48A3EBB2A39C" -Member 78f2fdb ..._x000D__x000A_</S><S S="Error">+                                                           ~~~~~~~_x000D__x000A_</S><S S="Error">    + CategoryInfo          : InvalidArgument: (:) [Add-ADGroupMember], ParameterBindingException_x000D__x000A_</S><S S="Error">    + FullyQualifiedErrorId : AmbiguousParameter,Microsoft.ActiveDirectory.Management.Commands.AddADGroupMember_x000D__x000A_</S><S S="Error"> _x000D__x000A_</S></Objs>, stdout: [0m`

**Comment by faisaleem-na** [comment]
apologies i found what you were asking for in the trace i think

is this what you wanted?

`2021-01-04T22:31:06.0232732Z 2021-01-04T22:31:05.436Z [DEBUG] plugin.terraform-provider-ad_v0.4.0_x5: 2021/01/04 22:31:05 [WARN] Truncating attribute path of 0 diagnostics for TypeSet
2021-01-04T22:31:06.0234197Z 2021-01-04T22:31:05.436Z [DEBUG] plugin.terraform-provider-ad_v0.4.0_x5: 2021/01/04 22:31:05 [DEBUG] Running command Add-ADGroupMember -Identity "726CC7A3-CDE9-4401-B0D0-48A3EBB2A39C" -Member d5fe91c8-7f18-494f-9764-febfb0d48dbe via powershell
2021-01-04T22:31:06.0236310Z 2021-01-04T22:31:05.436Z [DEBUG] plugin.terraform-provider-ad_v0.4.0_x5: 2021/01/04 22:31:05 [DEBUG] Encoded command: powershell.exe -EncodedCommand `

**Comment by faisaleem-na** [comment]
ok so tried that exact same command directly on the domain controller and got the same error message.

its because the input parameter should be -members not -member

there doesnt seem to be a -member parameter

**Comment by koikonom** [comment]
Thanks @faisaleem-na for reporting this and @jpatigny for helping! I will merge #68 right away. 

It looks like -Member is acceptable in version of the AD module that ships with windows 2012R2, which explains why the tests passed when I tried it. 

```
PS C:\Users\Administrator> Add-ADGroupMember -identity $group -members $user
PS C:\Users\Administrator> Add-ADGroupMember -identity $group -member $user1
PS C:\Users\Administrator> Get-ADGroupMember -identity $group


distinguishedName : CN=k o,CN=Users,DC=yourdomain,DC=com
name              : k o
objectClass       : user
objectGUID        : <>
SamAccountName    : kyriakos
SID               : <>

distinguishedName : CN=tst123,CN=Users,DC=yourdomain,DC=com
name              : tst123
objectClass       : user
objectGUID        : <>
SamAccountName    : tst123
SID               : <>
```

**Comment by faisaleem-na** [comment]
hi koikonom
right, understood, that makes sense now.
any chance of changing this to -members only or at least using -members if the OS is greater than 2012 R2?
i have Server 2019 domain controllers and -Member is not available :(
thanks

> Thanks @faisaleem-na for reporting this and @jpatigny for helping! I will merge #68 right away.
> 
> It looks like -Member is acceptable in version of the AD module that ships with windows 2012R2, which explains why the tests passed when I tried it.
> 
> ```
> PS C:\Users\Administrator> Add-ADGroupMember -identity $group -members $user
> PS C:\Users\Administrator> Add-ADGroupMember -identity $group -member $user1
> PS C:\Users\Administrator> Get-ADGroupMember -identity $group
> 
> 
> distinguishedName : CN=k o,CN=Users,DC=yourdomain,DC=com
> name              : k o
> objectClass       : user
> objectGUID        : <>
> SamAccountName    : kyriakos
> SID               : <>
> 
> distinguishedName : CN=tst123,CN=Users,DC=yourdomain,DC=com
> name              : tst123
> objectClass       : user
> objectGUID        : <>
> SamAccountName    : tst123
> SID               : <>
> ```

hi koikonom
right, understood, that makes sense now.
any chance of changing this to -members only or at least using -members if the OS is greater than 2012 R2?
i have Server 2019 domain controllers and -Member is not available :(
thanks

**Comment by faisaleem-na** [comment]
ignore me, just saw the jpatigny has already merged with this change to -Members
thanks
