### ISSUE TITLE
Make the use of WinRM optional if we're running on a windows machine.

### ISSUE THREAD

**Issue by koikonom** [hashicorp/terraform-provider-ad#70]
@jpatigny made an interesting point in https://github.com/hashicorp/terraform-provider-ad/issues/34#issuecomment-705011343 regarding the use of the provider within a windows container. That could potentially allow the provider to run without having to worry about authenticating.

The general idea would be for the provider to run the powershell commands directly instead of using winRM if :
- It's running on Windows.
- There are no credentials defined at all.
- <TBD>

**Comment by jpatigny** [comment]
PR made for this implementation.
Feel free to review/comment

**Comment by koikonom** [comment]
Thank you so much for this! I will take a good look at it this week and get back to you.

**Comment by jpatigny** [comment]
@koikonom , I think you can close this one 👍
