### ISSUE TITLE
Create AD user disabled/enabled

### ISSUE THREAD

**Issue by Lucero7919** [hashicorp/terraform-provider-ad#87]
### Description

Please allow an enabled/ disabled attribute (default enabled)

### Potential Terraform Configuration

No idea

### References

In a typical DIAD, user accounts are provisioned from a disabled User Templates, which offer tiered delegation and "just enough" rights to get the new user up to speed. New users are copied from this template. The additional roles of the new user are then populated as required. These templated users are disabled and have no password. Terraform should be able to create users and provision them as enabled or disabled using an attribute. (Default enabled).

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jpatigny** [comment]
Hello @Lucero7919 ,

If you look that the documentation you'll see that the "enable" attribute is available.

[doc for user resource](https://github.com/hashicorp/terraform-provider-ad/blob/main/docs/resources/user.md)

``
enabled (Boolean, Optional) If set to false, the user will be disabled.
``

**Comment by Lucero7919** [comment]
> Hello @Lucero7919 ,
> 
> If you look that the documentation you'll see that the "enable" attribute is available.
> 
> [doc for user resource](https://github.com/hashicorp/terraform-provider-ad/blob/main/docs/resources/user.md)
> 
> `enabled (Boolean, Optional) If set to false, the user will be disabled.`

Ah, sorry, my bad, I just saw all the attributes. Perfect, thank you
