### ISSUE TITLE
Support for double hop authentication

### ISSUE THREAD

**Issue by koikonom** [hashicorp/terraform-provider-ad#99]
Based on the feedback we have gathered so far from the community a common pattern
in managing AD is not to login to a Domain Controller directly, but instead login
to another machine and run the management tools there as a user that has enough
permissions to perform the administrative tasks.

The major drawback we encountered during testing was that although delegation was
working fine from a powershell session running on server other than the DC, doing
the same while running commands over WinRM on the same server was not working.

With the help of @gramsa49 we found out that we could work around the issue by creating a credential object and passing that object to the command. This solution is now part of the provider since version 0.4.3.

-------------- Old plan below, has been abandoned in favour of the approach merged in #117  -----------
 The method that worked is to use SSH[[0]] to login to a server and establish a powershell
session from which we could then run all the necessary commands to manage AD objects.

The setup we used looks like this:

```
                 +--------+      +-----------------+
Provider---SSH---|Server A|------|Domain Controller|
                 +--------+      +-----------------+
```

The requirements will be:
* Server A listens for SSH connections
* A domain user with the permissions required to run the powershell commands is used 
  to authenticate to Server A

The end result will be the provider performing the equivalent of this: 
```
❯ ssh ServerA cmd.exe /c 'powershell.exe -NonInteractive -Command {Get-ADUser testuser|convertto-json}'
testuser@ServerA's password:
{
    "GivenName":  "Test",
    "Surname":  "User",
    "UserPrincipalName":  "testuser@yourdomain.com",
    "Enabled":  true,
    "SamAccountName":  "testuser",
    "SID":  {
                "BinaryLength":  28,
                "AccountDomainSid":  {
                                         "BinaryLength":  24,
                                         "AccountDomainSid":  "S-1-5-21-3581563161-521910547-723215506",
                                         "Value":  "S-1-5-21-3581563161-521910547-723215506"
                                     },
                "Value":  "S-1-5-21-3581563161-521910547-723215506-1857"
            },
    "DistinguishedName":  "CN=Test User,CN=Users,DC=yourdomain,DC=com",
    "Name":  "Test User",
    "ObjectClass":  "user",
    "ObjectGuid":  "e0a42b9d-82a1-411a-a10a-cc8c3d8c4b76",
    "PropertyNames":  [
                          "DistinguishedName",
                          "Enabled",
                          "GivenName",
                          "Name",
                          "ObjectClass",
                          "ObjectGUID",
                          "SamAccountName",
                          "SID",
                          "Surname",
                          "UserPrincipalName"
                      ],
    "AddedProperties":  [
                        ],
    "RemovedProperties":  [
                          ],
    "ModifiedProperties":  [
                           ],
    "PropertyCount":  10,
    "ObjectGUID":  "e0a42b9d-82a1-411a-a10a-cc8c3d8c4b76"
}
```

[0]: https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse

**Comment by koikonom** [comment]
Hi @eramnes, @briantist, @jpatigny. I thought I'd bring this to your attention since you made some valid points about dropping the requirement for direct access to a DC.

**Comment by briantist** [comment]
thanks for opening this @koikonom . I've only skimmed this but I can say running SSH for the purposes of getting around double-hop (or for any purpose really) is likely to be a non-starter in any company where there isn't already a need for SSH on Windows.

I would think setting up CredSSP, or as I mentioned on another issue, a properly managed PowerShell Remoting Session Configuration (with or without the features of JEA) with a run-as account, would be a preferred way to address this. 

Just my 2 cents.

**Comment by Type1J** [comment]
I'm guessing that this issue is probably that there needs to be some sort of `socat` layer before the actual work is done. I have 2 questions:
1. I have many AWS environments that I manage, all of which are mixed Windows and Linux machines. A Linux bastion server with `ssh` is the only way into the environments. Can the provider get to what it needs by using the Linux `ssh` bastion with AD user that can admin the DC?
2. I know that in more Windows dominate AWS environments the bastion is Windows with RDP open. Can that be used to hop?
I'm not really sure where the authentication or tickets are needed.

**Comment by jpatigny** [comment]
@briantist,  

What you propose is to implement a solution similar to [(pypsrp)](https://github.com/jborean93/pypsrp) but i golang ?
I'm afraid it's above my (current) golang skill 👎🏻

**Comment by gramsa49** [comment]
I created a patch to enable passing the credentials to the remote powershell session over winrm.
I coded this to require https since passing credentials over an unenecrypted channel is insecure.

The PR is 103

**Comment by koikonom** [comment]
Double hop authentication is now part of the provider starting with version v0.4.3.
